version: "3"

services:
  timescaledb:
    container_name: "jobsity_db"
    image: "timescale/timescaledb-postgis:latest-pg12"
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: "jobsity"
      POSTGRES_PASSWORD: "admin123"
      PGUSER: "jobsity"
      PGPASSWORD: "admin123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${PWD}/data:/data
  ingestorapi:
    container_name: "jobsity_ingestor"
    image: "vitorhmendes97/jobsity-ingestor:latest"
    ports: ["5000:5000"]
    depends_on:
      - "timescaledb"
    environment:
       POSTGRES_DB_HOST: ""
       POSTGRES_DB_USER: "jobsity"
       POSTGRES_DB_PWD: "admin123"
       POSTGRES_TABLE_NAME: "trips"
       INGESTION_FILE_PATH: "/data/landing"
       INGESTION_PROCESSED_PATH: "/data/processed"
       NOTIFICATION_EMAIL_USER_LOGIN: ""
       NOTIFICATION_EMAIL_USER_PWD: ""
    volumes:
      - ${PWD}/data:/data
volumes:
  postgres-data:
